// SPDX-FileCopyrightText: 2025-present Kriasoft
// SPDX-License-Identifier: MIT

/**
 * Reserved server-only meta keys.
 *
 * These keys are used for server-controlled metadata and cannot be overridden
 * by clients. The router enforces this through defense-in-depth:
 *
 * - **Design-time**: Schema creation throws if extended meta defines these keys
 * - **Runtime**: Inbound messages have these keys stripped before validation
 *
 * This prevents client spoofing of server-controlled timestamps and identifiers.
 *
 * Reference: specs/rules.md#reserved-keys
 * Implementation: specs/validation.md#normalization-rules
 */
export const RESERVED_META_KEYS = new Set<string>([
  "clientId", // UUID v7 generated by server on connection
  "receivedAt", // Server ingress timestamp, set by router
]);

/**
 * Type for reserved meta key literals.
 *
 * Useful for type-safe operations on reserved keys.
 */
export type ReservedMetaKey = "clientId" | "receivedAt";

/**
 * Default configuration values.
 *
 * These are used if not overridden in WebSocketRouterOptions.
 */
export const DEFAULT_CONFIG = {
  /** Default ping interval (30 seconds) */
  HEARTBEAT_INTERVAL_MS: 30_000,

  /** Default pong timeout (5 seconds) */
  HEARTBEAT_TIMEOUT_MS: 5_000,

  /** Default max payload size (1 MB) */
  MAX_PAYLOAD_BYTES: 1_000_000,

  /** Default server ingress timestamp field in meta */
  TIMESTAMP_FIELD: "receivedAt",
} as const;
